import unittest
import sys
import logging
logger = logging.getLogger(__name__)

from pylatexenc.macrospec._latexcontextdb import (
    LatexContextDb,
    _autogen_category_prefix
)

from pylatexenc.macrospec import (
    MacroSpec,
    EnvironmentSpec,
    SpecialsSpec,
)



class TestLatexContextDb(unittest.TestCase):


    # TODO........ need more tests here


    def _make_shadowed_db(self, **kwargs):
        r"""
        Build a context db with three categories 'A', 'B' and 'C', each of which
        defines the very same macro, environment and specials.  The category 'C'
        is registered with whichever options are given as keyword arguments.
        """
        db = LatexContextDb()
        for cat in ('A', 'B',):
            db.add_context_category(
                cat,
                macros=[ MacroSpec('m', ''), ],
                environments=[ EnvironmentSpec('e', ''), ],
                specials=[ SpecialsSpec('&'), ],
            )
        db.add_context_category(
            'C',
            macros=[ MacroSpec('m', ''), ],
            environments=[ EnvironmentSpec('e', ''), ],
            specials=[ SpecialsSpec('&'), ],
            **kwargs
        )
        return db

    def _assert_first_category_wins_lookups(self, db, expected_categories):
        r"""
        Check that the category order is `expected_categories` and that all the
        lookups of the definitions that the categories shadow one another do
        indeed resolve to the definition in the first of those categories.
        """
        self.assertEqual(db.categories(), expected_categories)
        first_cat = db.categories()[0]
        self.assertIs(db.get_macro_spec('m'),
                      db.d[first_cat]['macros']['m'])
        self.assertIs(db.get_environment_spec('e'),
                      db.d[first_cat]['environments']['e'])
        self.assertIs(db.get_specials_spec('&'),
                      db.d[first_cat]['specials']['&'])
        # test_for_specials() searches the categories in the same order
        self.assertIs(db.test_for_specials('&', 0),
                      db.d[first_cat]['specials']['&'])

    def test_add_context_category_append(self):
        self._assert_first_category_wins_lookups(
            self._make_shadowed_db(),
            ['A', 'B', 'C']
        )

    def test_add_context_category_prepend(self):
        self._assert_first_category_wins_lookups(
            self._make_shadowed_db(prepend=True),
            ['C', 'A', 'B']
        )

    def test_add_context_category_insert_before_first(self):
        self._assert_first_category_wins_lookups(
            self._make_shadowed_db(insert_before='A'),
            ['C', 'A', 'B']
        )

    def test_add_context_category_insert_before_later(self):
        self._assert_first_category_wins_lookups(
            self._make_shadowed_db(insert_before='B'),
            ['A', 'C', 'B']
        )

    def test_add_context_category_insert_before_unknown(self):
        self._assert_first_category_wins_lookups(
            self._make_shadowed_db(insert_before='no-such-category'),
            ['C', 'A', 'B']
        )

    def test_add_context_category_insert_after_first(self):
        self._assert_first_category_wins_lookups(
            self._make_shadowed_db(insert_after='A'),
            ['A', 'C', 'B']
        )

    def test_add_context_category_insert_after_last(self):
        self._assert_first_category_wins_lookups(
            self._make_shadowed_db(insert_after='B'),
            ['A', 'B', 'C']
        )

    def test_add_context_category_insert_after_unknown(self):
        self._assert_first_category_wins_lookups(
            self._make_shadowed_db(insert_after='no-such-category'),
            ['A', 'B', 'C']
        )


    def test_extended_with_copies_category_list(self):

        context = LatexContextDb()
        context.add_context_category(
            'base-category',
            macros=[ MacroSpec('base', '{'), ],
        )
        context.freeze()

        # the first extended_with() creates a new autogenerated category ...
        context2 = context.extended_with(macros=[ MacroSpec('more', '{'), ])
        # ... and the second one merges its definitions into that same
        # autogenerated category; it must still get its own copy of the list of
        # categories rather than share the one of the object it extends
        context3 = context2.extended_with(macros=[ MacroSpec('evenmore', '{'), ])

        self.assertEqual(context3.category_list, context2.category_list)
        self.assertIsNot(context3.category_list, context2.category_list)


    def test_extended_with(self):

        context = LatexContextDb()
        context.add_context_category(
            'base-category',
            macros=[ MacroSpec('base', '{'), ],
            environments=[ EnvironmentSpec('baseenv', '{'), ],
            specials=[ SpecialsSpec('~'), ],
        )
        context.freeze()

        logger.debug("context's category list = %r", context.category_list)
        logger.debug("context's d = %r", context.d)
        logger.debug("context's lookup maps are = %r", context.lookup_chain_maps)

        extd1 = dict(
            macros=[ MacroSpec('more', '{'), ],
            environments=[ EnvironmentSpec('moreenv', '{'), ],
            specials=[ SpecialsSpec('!'), ],
        )
        context2 = context.extended_with(**extd1)
    
        logger.debug("context2's category list = %r", context2.category_list)
        logger.debug("context2's d = %r", context2.d)
        logger.debug("context2's lookup maps are = %r", context2.lookup_chain_maps)

        self.assertEqual(len(context2.category_list), 2)
        self.assertTrue(context2.category_list[0].startswith(_autogen_category_prefix))

        self.assertEqual(context2.get_macro_spec('base'),
                         context.get_macro_spec('base'))
        self.assertEqual(context2.get_environment_spec('baseenv'),
                         context.get_environment_spec('baseenv'))
        self.assertEqual(context2.get_specials_spec('~'),
                         context.get_specials_spec('~'))
        self.assertEqual(context2.test_for_specials('~~~~~~~', pos=0),
                         context.get_specials_spec('~'))
        self.assertEqual(context2.get_macro_spec('more'), extd1['macros'][0])
        self.assertEqual(context2.get_environment_spec('moreenv'), extd1['environments'][0])
        self.assertEqual(context2.get_specials_spec('!'), extd1['specials'][0])
        self.assertEqual(context2.test_for_specials('!!!!!', pos=0), extd1['specials'][0])

        extd2 = dict(
            macros=[ MacroSpec('evenmore', '{'), ],
            environments=[ EnvironmentSpec('baseenv', '{'), ], # override baseenv
            specials=[ SpecialsSpec('!!'), ],
        )
        context3 = context2.extended_with(**extd2)
   
        # extended_with() a second time shouldn't add a new category as the
        # first category is already an autogenerated one
        self.assertEqual(len(context3.category_list), 2)
        self.assertEqual(context3.category_list, context2.category_list)
        self.assertTrue(context3.category_list[0].startswith(_autogen_category_prefix))

        logger.debug("context3's category list = %r", context3.category_list)
        logger.debug("context3's d = %r", context3.d)
        logger.debug("context3's lookup maps are = %r", context3.lookup_chain_maps)

        self.assertEqual(context3.get_macro_spec('base'),
                         context.get_macro_spec('base'))
        # self.assertEqual(context3.get_environment_spec('baseenv'),
        #                  context.get_environment_spec('baseenv')) # NO!
        self.assertEqual(context3.get_specials_spec('~'),
                         context.get_specials_spec('~'))
        self.assertEqual(context3.test_for_specials('~~~~~~~', pos=0),
                         context.get_specials_spec('~'))
        self.assertEqual(context3.get_macro_spec('more'), extd1['macros'][0])
        self.assertEqual(context3.get_macro_spec('evenmore'), extd2['macros'][0])
        self.assertEqual(context3.get_environment_spec('moreenv'), extd1['environments'][0])
        self.assertEqual(context3.get_environment_spec('baseenv'), extd2['environments'][0])
        self.assertEqual(context3.get_specials_spec('!'), extd1['specials'][0])
        self.assertEqual(context3.get_specials_spec('!!'), extd2['specials'][0])
        self.assertEqual(context3.test_for_specials('!!!!!', pos=0), extd2['specials'][0])





# ---

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    unittest.main()
#
