#
# Configuration for readthedocs.org
#

# See poetry builds on RTD:
# https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

version: 2

build:

  os: "ubuntu-22.04"

  tools:
    python: "3.10"

  jobs:

    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - 'pip install "poetry>=1.4"'

      # Tell poetry to not use a virtual environment
      - 'poetry config virtualenvs.create false'

    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - 'poetry install --with builddoc'


sphinx:
  configuration: doc/conf.py
  builder: 'dirhtml'
