# -*- coding: utf-8 -*-
#
# The MIT License (MIT)
# 
# Copyright (c) 2015 Philippe Faist
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#


#
# CHARACTER MAP TAKEN FROM latexcodec 0.2, by Peter Troeger
#    https://pypi.python.org/pypi/latexcodec
#
#
# latexcodec is a lexer and codec to work with LaTeX code in Python
# Copyright (c) 2011-2014 by Matthias C. M. Troffaes
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 
#



# generated by genmapping.py    ### PhF: ... and edited manually by myself
utf82latex = {
34:"''", 	# character "
35:'\\#', 	# character #
36:'\\$', 	# character $
37:'\\%', 	# character %
38:'\\&', 	# character &
0x003C: r'\ensuremath{<}', # <
0x003E: r'\ensuremath{>}', # >
92:'\\textbackslash', # the \ character itself
95:'\\_', 	# character _
123:'\\{', 	# character {
125:'\\}', 	# character }
126:'\\textasciitilde', # character ~
160:'~', 	# character  
161:'\\textexclamdown', 	# character ¡
162:'\\textcent', 	# character ¢
163:'\\textsterling', 	# character £
164:'\\textcurrency', 	# character €
165:'\\textyen', 	# character ¥
166:'\\textbrokenbar', 	# character Š
167:'\\textsection', 	# character §
168:'\\textasciidieresis', 	# character š
169:'\\textcopyright', 	# character ©
170:'\\textordfeminine', 	# character ª
171:'\\guillemotleft', 	# character «
172:'\\textlnot', 	# character ¬
174:'\\textregistered', 	# character ®
175:'\\textasciimacron', 	# character ¯
176:'\\textdegree', 	# character °
177:'\\ensuremath{\\pm}', 	# character ±
178:'\\texttwosuperior', 	# character ²
179:'\\textthreesuperior', 	# character ³
180:'\\textasciiacute', 	# character Ž
181:'\\textmu', 	# character µ
182:'\\textparagraph', 	# character ¶
183:'\\textperiodcentered', 	# character ·
185:'\\textonesuperior', 	# character ¹
186:'\\textordmasculine', 	# character º
187:'\\guillemotright', 	# character »
188:'\\textonequarter', 	# character Œ
189:'\\textonehalf', 	# character œ
190:'\\textthreequarters', 	# character Ÿ
191:'\\textquestiondown', 	# character ¿
192:'\\`A', 	# character À
193:"\\'A", 	# character Á
194:'\\^A', 	# character Â
195:'\\~A', 	# character Ã
196:'\\"A', 	# character Ä
197:'\\r{A}', 	# character Å
198:'\\AE', 	# character Æ
199:'\\c{C}', 	# character Ç
200:'\\`E', 	# character È
201:"\\'E", 	# character É
202:'\\^E', 	# character Ê
203:'\\"E', 	# character Ë
204:'\\`I', 	# character Ì
205:"\\'I", 	# character Í
206:'\\^I', 	# character Î
207:'\\"I', 	# character Ï
208:'\\DH', 	# character Ð
209:'\\~N', 	# character Ñ
210:'\\`O', 	# character Ò
211:"\\'O", 	# character Ó
212:'\\^O', 	# character Ô
213:'\\~O', 	# character Õ
214:'\\"O', 	# character Ö
215:'\\texttimes', 	# character ×
216:'\\O', 	# character Ø
217:'\\`U', 	# character Ù
218:"\\'U", 	# character Ú
219:'\\^U', 	# character Û
220:'\\"U', 	# character Ü
221:"\\'Y", 	# character Ý
222:'\\TH', 	# character Þ
223:'\\ss', 	# character ß
224:'\\`a', 	# character à
225:"\\'a", 	# character á
226:'\\^a', 	# character â
227:'\\~a', 	# character ã
228:'\\"a', 	# character ä
229:'\\r{a}', 	# character å
230:'\\ae', 	# character æ
231:'\\c{c}', 	# character ç
232:'\\`e', 	# character è
233:"\\'e", 	# character é
234:'\\^e', 	# character ê
235:'\\"e', 	# character ë
236:'\\`\\i', 	# character ì
237:"\\'\\i", 	# character í
238:'\\^\\i', 	# character î
239:'\\"\\i', 	# character ï
240:'\\dh', 	# character ð
241:'\\~n', 	# character ñ
242:'\\`o', 	# character ò
243:"\\'o", 	# character ó
244:'\\^o', 	# character ô
245:'\\~o', 	# character õ
246:'\\"o', 	# character ö
247:'\\textdiv', 	# character ÷
248:'\\o', 	# character ø
249:'\\`u', 	# character ù
250:"\\'u", 	# character ú
251:'\\^u', 	# character û
252:'\\"u', 	# character ü
253:"\\'y", 	# character ý
254:'\\th', 	# character þ
255:'\\"y', 	# character ÿ
256:'\\={A}',
257:'\\={a}',
258:'\\u{A}',
259:'\\u{a}',
260:'\\k{A}',
261:'\\k{a}',
262:"\\'C",
263:"\\'c",
264:'\\^{C}',
265:'\\^{c}',
266:'\\.{C}',
267:'\\.{c}',
268:'\\v{C}',
269:'\\v{c}',
270:'\\v{D}',
271:'\\v{d}',
272:'\\DJ',
273:'\\dj',
274:'\\={E}',
275:'\\={e}',
276:'\\u{E}',
277:'\\u{e}',
278:'\\.{E}',
279:'\\.{e}',
280:'\\k{E}',
281:'\\k{e}',
282:'\\v{E}',
283:'\\v{e}',
284:'\\^{G}',
285:'\\^{g}',
286:'\\u{G}',
287:'\\u{g}',
288:'\\.{G}',
289:'\\.{g}',
290:'\\c{G}',
291:'\\c{g}',
292:'\\^{H}',
293:'\\^{h}',
294:'\\={H}',
295:'\\={h}',
296:'\\~{I}',
297:'\\~{i}',
298:'\\={I}',
299:'\\={i}',
300:'\\u{I}',
301:'\\u{i}',
302:'\\k{I}',
303:'\\k{i}',
304:'\\.I',
305:'\\i',
306:'\\IJ',
307:'\\ij',
308:'\\^{J}',
309:'\\^{j}',
310:'\\c{K}',
311:'\\c{k}',
312:'\\textsc\{k\}',
313:"\\'L",
314:"\\'l",
315:'\\c{L}',
316:'\\c{l}',
317:'\\v{L}',
318:'\\v{l}',
319:'\\.{L}',
320:'\\.{l}',
321:'\\L',
322:'\\l',
323:"\\'N",
324:"\\'n",
325:'\\c{N}',
326:'\\c{n}',
327:'\\v{N}',
328:'\\v{n}',
329:'\\nument{149}',
330:'\\NG',
331:'\\ng',
332:'\\={O}',
333:'\\={o}',
334:'\\u{O}',
335:'\\u{o}',
336:"\\H{O}",
337:"\\H{o}",
338:'\\OE',
339:'\\oe',
340:"\\'R",
341:"\\'r",
342:'\\c{R}',
343:'\\c{r}',
344:'\\v{R}',
345:'\\v{r}',
346:"\\'S",
347:"\\'s",
348:'\\^{S}',
349:'\\^{s}',
350:'\\c{S}',
351:'\\c{s}',
352:'\\v{S}',
353:'\\v{s}',
354:'\\c{T}',
355:'\\c{t}',
356:'\\v{T}',
357:'\\v{t}',
358:'\\={T}',
359:'\\={t}',
360:'\\~{U}',
361:'\\~{u}',
362:'\\={U}',
363:'\\={u}',
364:'\\u{U}',
365:'\\u{u}',
366:'\\r{U}',
367:'\\r{u}',
368:"\\'{U}",
369:"\\'{u}",
370:'\\k{U}',
371:'\\k{u}',
372:'\\^{W}',
373:'\\^{w}',
374:'\\^{Y}',
375:'\\^{y}',
376:'\\"Y',
377:"\\'Z",
378:"\\'z",
379:'\\.Z',
380:'\\.z',
381:'\\v{Z}',
382:'\\v{z}',
402:'\\textflorin', # 0x0192

0x0228: r'\c{E}',
0x0229: r'\c{e}',

710:'\\textasciicircum', # 0x02C6
711:'\\textasciicaron',
728:'\\textasciibreve',
732:'\\textasciitilde',
733:'\\textacutedbl', # 0x02DD


# ---------------------

0x02BC: r"'", # MODIFIER LETTER APOSTROPHE

# Combining Diacritical Marks (!!TODO!! smarter)
0x0307: r'\ensuremath{\dot{}}',
0x0308: r'\ensuremath{\ddot{}}',

0x0391: r'A', # GREEK CAPITAL LETTER ALPHA
0x0392: r'B', # GREEK CAPITAL LETTER BETA
0x0393: r'\ensuremath{\Gamma}', # GREEK CAPITAL LETTER GAMMA
0x0394: r'\ensuremath{\Delta}', # ...
0x0395: r'E',
0x0396: r'Z',
0x0397: r'H',
0x0398: r'\ensuremath{\Theta}',
0x0399: r'I',
0x039A: r'K',
0x039B: r'\ensuremath{\Lambda}',
0x039C: r'M',
0x039D: r'N',
0x039E: r'\ensuremath{\Xi}',
0x039F: r'O',
0x03A0: r'\ensuremath{\Pi}',
0x03A1: r'P',
0x03A3: r'\ensuremath{\Sigma}',
0x03A4: r'T',
0x03A5: r'\ensuremath{\Upsilon}',
0x03A6: r'\ensuremath{\Phi}',
0x03A7: r'X',
0x03A8: r'\ensuremath{\Psi}',
0x03A9: r'\ensuremath{\Omega}',
# tonos letters [ ... ]
0x03B1: r'\ensuremath{\alpha}', # Greek Small Letter Alpha
0x03B2: r'\ensuremath{\beta}',
0x03B3: r'\ensuremath{\gamma}',
0x03B4: r'\ensuremath{\delta}',
0x03B5: r'\ensuremath{\varepsilon}',
0x03B6: r'\ensuremath{\zeta}',
0x03B7: r'\ensuremath{\eta}',
0x03B8: r'\ensuremath{\theta}',
0x03B9: r'\ensuremath{\i}',
0x03BA: r'\ensuremath{\kappa}',
0x03BB: r'\ensuremath{\lambda}',
0x03BC: r'\ensuremath{\mu}',
0x03BD: r'\ensuremath{\nu}',
0x03BE: r'\ensuremath{\xi}',
0x03BF: r'o',
0x03C0: r'\ensuremath{\pi}',
0x03C1: r'\ensuremath{\rho}',
0x03C2: r'\ensuremath{\varsigma}',
0x03C3: r'\ensuremath{\sigma}',
0x03C4: r'\ensuremath{\tau}',
0x03C5: r'\ensuremath{\upsilon}',
0x03C6: r'\ensuremath{\varphi}',
0x03C7: r'\ensuremath{\chi}',
0x03C8: r'\ensuremath{\psi}',
0x03C9: r'\ensuremath{\omega}',

0x03D1: r'\ensuremath{\vartheta}', # Greek Theta Symbol
0x03D5: r'\ensuremath{\phi}', # Greek Phi Symbol
0x03D6: r'\ensuremath{\varpi}', # Greek Pi Symbol
0x03F1: r'\ensuremath{\varrho}', # Greek rho symbol


1024:'\\`\\CYRE', # 0x0400
1025:'\\CYRYO',
1026:'\\CYRDJE',
1027:'\\`\\CYRG',
1028:'\\CYRIE',
1029:'\\CYRDZE',
1030:'\\CYRII',
1031:'\\CYRYI',
1032:'\\CYRJE',
1033:'\\CYRLJE',
1034:'\\CYRNJE',
1035:'\\CYRTSHE',
1036:'\\`\\CYRK',
1037:'\\`\\CYRI',
1038:'\\CYRUSHRT',
1039:'\\CYRDZHE',
1040:'\\CYRA',
1041:'\\CYRB',
1042:'\\CYRV',
1043:'\\CYRG',
1044:'\\CYRD',
1045:'\\CYRE',
1046:'\\CYRZH',
1047:'\\CYRZ',
1048:'\\CYRI',
1049:'\\CYRISHRT',
1050:'\\CYRK',
1051:'\\CYRL',
1052:'\\CYRM',
1053:'\\CYRN',
1054:'\\CYRO',
1055:'\\CYRP',
1056:'\\CYRR',
1057:'\\CYRS',
1058:'\\CYRT',
1059:'\\CYRU',
1060:'\\CYRF',
1061:'\\CYRH',
1062:'\\CYRC',
1063:'\\CYRCH',
1064:'\\CYRSH',
1065:'\\CYRSHCH',
1066:'\\CYRHRDSN',
1067:'\\CYRERY',
1068:'\\CYRSFTSN',
1069:'\\CYREREV',
1070:'\\CYRYU',
1071:'\\CYRYA',
1072:'\\cyra',
1073:'\\cyrb',
1074:'\\cyrv',
1075:'\\cyrg',
1076:'\\cyrd',
1077:'\\cyre',
1078:'\\cyrzh',
1079:'\\cyrz',
1080:'\\cyri',
1081:'\\cyrishrt',
1082:'\\cyrk',
1083:'\\cyrl',
1084:'\\cyrm',
1085:'\\cyrn',
1086:'\\cyro',
1087:'\\cyrp',
1088:'\\cyrr',
1089:'\\cyrs',
1090:'\\cyrt',
1091:'\\cyru',
1092:'\\cyrf',
1093:'\\cyrh',
1094:'\\cyrc',
1095:'\\cyrch',
1096:'\\cyrsh',
1097:'\\cyrshch',
1098:'\\cyrhrdsn',
1099:'\\cyrery',
1100:'\\cyrsftsn',
1101:'\\cyrerev',
1102:'\\cyryu',
1103:'\\cyrya',
1104:'\\`\\cyre',
1105:'\\cyryo',
1106:'\\cyrdje',
1107:'\\`\\cyrg',
1108:'\\cyrie',
1109:'\\cyrdze',
1110:'\\cyrii',
1111:'\\cyryi',
1112:'\\cyrje',
1113:'\\cyrlje',
1114:'\\cyrnje',
1115:'\\cyrtshe',
1116:'\\`\\cyrk',
1117:'\\`\\cyri',
1118:'\\cyrushrt',
1119:'\\cyrdzhe',
1122:'\\CYRYAT',
1123:'\\cyryat',
1130:'\\CYRBYUS',
1131:'\\cyrbyus',
1138:'\\CYRFITA',
1139:'\\cyrfita',
1140:'\\CYRIZH',
1141:'\\cyrizh',
1142:'\\C\\CYRIZH',
1143:'\\C\\cyrizh',
1164:'\\CYRSEMISFTSN',
1165:'\\cyrsemisftsn',
1166:'\\CYRRTICK',
1167:'\\cyrrtick',
1168:'\\CYRGUP',
1169:'\\cyrgup',
1170:'\\CYRGHCRS',
1171:'\\cyrghcrs',
1172:'\\CYRGHK',
1173:'\\cyrghk',
1174:'\\CYRZHDSC',
1175:'\\cyrzhdsc',
1176:'\\CYRZDSC',
1177:'\\cyrzdsc',
1178:'\\CYRKDSC',
1179:'\\cyrkdsc',
1180:'\\CYRKVCRS',
1181:'\\cyrkvcrs',
1182:'\\CYRKHCRS',
1183:'\\cyrkhcrs',
1184:'\\CYRKBEAK',
1185:'\\cyrkbeak',
1186:'\\CYRNDSC',
1187:'\\cyrndsc',
1188:'\\CYRNG',
1189:'\\cyrng',
1190:'\\CYRPHK',
1191:'\\cyrphk',
1192:'\\CYRABHHA',
1193:'\\cyrabhha',
1194:'\\CYRSDSC',
1195:'\\cyrsdsc',
1196:'\\CYRTDSC',
1197:'\\cyrtdsc',
1198:'\\CYRY',
1199:'\\cyry',
1200:'\\CYRYHCRS',
1201:'\\cyryhcrs',
1202:'\\CYRHDSC',
1203:'\\cyrhdsc',
1204:'\\CYRTETSE',
1205:'\\cyrtetse',
1206:'\\CYRCHRDSC',
1207:'\\cyrchrdsc',
1208:'\\CYRCHVCRS',
1209:'\\cyrchvcrs',
1210:'\\CYRSHHA',
1211:'\\cyrshha',
1212:'\\CYRABHCH',
1213:'\\cyrabhch',
1214:'\\CYRABHCHDSC',
1215:'\\cyrabhchdsc',
1216:'\\CYRpalochka',
1217:'\\U\\CYRZH',
1218:'\\U\\cyrzh',
1219:'\\CYRKHK',
1220:'\\cyrkhk',
1221:'\\CYRLDSC',
1222:'\\cyrldsc',
1223:'\\CYRNHK',
1224:'\\cyrnhk',
1227:'\\CYRCHLDSC',
1228:'\\cyrchldsc',
1229:'\\CYRMDSC',
1230:'\\cyrmdsc',
1232:'\\U\\CYRA',
1233:'\\U\\cyra',
1234:'\\"\\CYRA',
1235:'\\"\\cyra',
1236:'\\CYRAE',
1237:'\\cyrae',
1238:'\\U\\CYRE',
1239:'\\U\\cyre',
1240:'\\CYRSCHWA',
1241:'\\cyrschwa',
1242:'\\"\\CYRSCHWA',
1243:'\\"\\cyrschwa',
1244:'\\"\\CYRZH',
1245:'\\"\\cyrzh',
1246:'\\"\\CYRZ',
1247:'\\"\\cyrz',
1248:'\\CYRABHDZE',
1249:'\\cyrabhdze',
1250:'\\=\\CYRI',
1251:'\\=\\cyri',
1252:'\\"\\CYRI',
1253:'\\"\\cyri',
1254:'\\"\\CYRO',
1255:'\\"\\cyro',
1256:'\\CYROTLD',
1257:'\\cyrotld',
1260:'\\"\\CYREREV',
1261:'\\"\\cyrerev',
1262:'\\=\\CYRU',
1263:'\\=\\cyru',
1264:'\\"\\CYRU',
1265:'\\"\\cyru',
1266:'\\H\\CYRU',
1267:'\\H\\cyru',
1268:'\\"\\CYRCH',
1269:'\\"\\cyrch',
1270:'\\CYRGDSC',
1271:'\\cyrgdsc',
1272:'\\"\\CYRERY',
1273:'\\"\\cyrery',
1274:'\\CYRGDSCHCRS',
1275:'\\cyrgdschcrs',
1276:'\\CYRHHK',
1277:'\\cyrhhk',
1278:'\\CYRHHCRS',
1279:'\\cyrhhcrs', # 0x04FF

    
0x0E3F: r'\textbaht',


# spaces
0x2000: r'\enskip', # EN QUAD (= EN SPACE U+2002)
0x2001: r'\quad', # EM QUAD (= EM SPACE U+2003)
0x2002: r'\enskip', # EN SPACE
0x2003: r'\quad', # EM SPACE
0x2004: r'\hspace{0.33em}', # THREE-PER-EM SPACE
0x2005: r'\hsapce{0.25em}', # FOUR-PER-EM SPACE
0x2006: r'\hspace{0.167em}', # SIX-PER-EM SPACE
0x2007: r'~', # FIGURE SPACE
0x2008: r'\;', # PUNCTUATION SPACE
0x2009: r'\,', # thin space
0x200A: r'\hspace{1pt}', # supposed to be thinnest typographical space available

0x200C: r'\textcompwordmark', # ZERO WIDTH NON-JOINER

0x2010: r'-', # HYPHEN
0x2011: r'\nobreakdash-', # NON-BREAKING HYPHEN, https://tex.stackexchange.com/a/330437/32188
0x2012: r'-', # FIGURE DASH
0x2013:'\\textendash', # 0x2013
0x2014:'\\textemdash',
0x2015:'\\textemdash', # HORIZONTAL BAR
0x2016:'\\textbardbl',
0x2018:'\\textquoteleft',
0x2019:'\\textquoteright',
8218:'\\quotesinglbase', # 0x201A
8220:'\\textquotedblleft',
8221:'\\textquotedblright',
8222:'\\quotedblbase',
8224:'\\textdagger',
8225:'\\textdaggerdbl',
8226:'\\textbullet',
8230:'\\textellipsis',
8240:'\\textperthousand',
8241:'\\textpertenthousand',
8249:'\\guilsinglleft',
8250:'\\guilsinglright',
8251:'\\textreferencemark',
8253:'\\textinterrobang',
8260:'\\textfractionsolidus',
8270:'\\textasteriskcentered',
8274:'\\textdiscount', # 0x2052

0x2061: r'', # FUNCTION APPLICATION

8353:'\\textcolonmonetary', # 0x20A1
8356:'\\textlira',
8358:'\\textnaira',
8361:'\\textwon',
8363:'\\textdong',
8364:'\\texteuro',
8369:'\\textpeso', # 0x20B1


# letter-like symbols
0x2102: r'\ensuremath{\mathbb{C}}', # DOUBLE-STRUCK CAPITAL C
0x2103: r'\textcelsius', # DEGREE CELSIUS
0x2109: r'\ensuremath{^\circ}F', # DEGREE FARENHEIT
0x210A: r'\ensuremath{g}', # SCRIPT SMALL G
0x210B: r'\ensuremath{\mathscr{H}}', # SCRIPT CAPITAL H
0x210C: r'\ensuremath{\mathfrak{H}}', # BLACK-LETTER CAPITAL H
0x210D: r'\ensuremath{\mathbb{H}}', # DOUBLE-STRUCK CAPITAL H
0x210E: r'\ensuremath{h}', # PLANCK CONSTANT
0x210F: r'\ensuremath{\hbar}', # h bar, PLANCK CONSTANT OVER TWO PI
0x2110: r'\ensuremath{\mathscr{I}}', # SCRIPT CAPITAL I
0x2111: r'\ensuremath{\mathfrak{I}}', # BLACK-LETTER CAPITAL I
0x2112: r'\ensuremath{\mathscr{L}}', # SCRIPT CAPITAL L
0x2113: r'\ensuremath{\ell}', # SCRIPT SMALL L
0x2115: r'\ensuremath{\mathbb{N}}', # DOUBLE-STRUCK CAPITAL N
0x2116: r'\textnumero', # NUMERO SIGN
0x2117: r'\textcircledP', # SOUND RECORDING COPYRIGHT
0x211E: r'\textrecipe', # PRESCRIPTION TAKE
0x2119: r'\ensuremath{\mathbb{P}}', # DOUBLE-STRUCK CAPITAL P
0x211A: r'\ensuremath{\mathbb{Q}}', # DOUBLE-STRUCK CAPITAL Q
0x211B: r'\ensuremath{\mathscr{R}}', # SCRIPT CAPITAL R
0x211C: r'\ensuremath{\mathfrak{R}}', # BLACK-LETTER CAPITAL R
0x211D: r'\ensuremath{\mathbb{R}}', # DOUBLE-STRUCK CAPITAL R
0x2120: r'\textservicemark', # SERVICE MARK
0x2122: r'\texttrademark', # TRADE MARK SIGN
0x2124: r'\ensuremath{\mathbb{Z}}', # DOUBLE-STRUCK CAPITAL Z
0x2126: r'\textohm', # OHM SIGN
0x2127: r'\textmho', # OHM SIGN
0x2128: r'\ensuremath{\mathfrak{Z}}', # BLACK-LETTER CAPITAL Z
0x212A: r'K', # KELVIN SIGN
0x212B: r'\r{A}', # ANGSTROM SIGN
0x212C: r'\ensuremath{\mathscr{B}}', # SCRIPT CAPITAL B
0x212D: r'\ensuremath{\mathfrak{C}}', # BLACK-LETTER CAPITAL C
0x212E: r'\textestimated', # ESTIMATED SYMBOL
0x212F: r'\ensuremath{e}', # SCRIPT SMALL E
0x2130: r'\ensuremath{\mathscr{E}}', # SCRIPT CAPITAL E
0x2131: r'\ensuremath{\mathscr{F}}', # SCRIPT CAPITAL F
0x2133: r'\ensuremath{\mathscr{M}}', # SCRIPT CAPITAL M
0x2134: r'\ensuremath{o}', # SCRIPT SMALL O


8592:'\\textleftarrow', # 0x2190
8593:'\\textuparrow',
8594:'\\textrightarrow',
8595:'\\textdownarrow', # 0x2193


# Math operators and symbols (U+22XX)
0x2200: r'\ensuremath{\forall}',
0x2201: r'\ensuremath{\complement}',
0x2202: r'\ensuremath{\partial}',
0x2203: r'\ensuremath{\exists}',
0x2204: r'\ensuremath{\nexists}',
0x2205: r'\ensuremath{\varnothing}',
0x2206: r'\ensuremath{\Delta}',
0x2207: r'\ensuremath{\nabla}',
0x2208: r'\ensuremath{\in}',
0x2209: r'\ensuremath{\notin}',
0x220A: r'\ensuremath{\in}', # alternative
0x220B: r'\ensuremath{\ni}',
0x220C: r'\ensuremath{\not\ni}',
0x220D: r'\ensuremath{\ni}', # alternative
0x220E: r'\ensuremath{\blacksquare}',
0x220F: r'\ensuremath{\prod}',
0x2210: r'\ensuremath{\coprod}',
0x2211: r'\ensuremath{\sum}',
0x2212: r'\ensuremath{-}',
0x2213: r'\ensuremath{\mp}',
#0x2214: DOT PLUS
0x2215: r'\ensuremath{/}',
0x2216: r'\ensuremath{\smallsetminus}',
0x2217: r'\ensuremath{*}',
0x2218: r'\ensuremath{\circ}',
0x2219: r'\ensuremath{\bullet}',
0x221A: r'\ensuremath{\sqrt{}}',
0x221B: r'\ensuremath{\sqrt[3]{}}',
0x221C: r'\ensuremath{\sqrt[4]{}}',
0x221D: r'\ensuremath{\propto}',
0x221E: r'\ensuremath{\infty}',
#0x221F: RIGHT ANGLE
#0x2220: ANGLE
#0x2221: MEASURED ANGLE
#0x2222: SPHERICAL ANGLE
0x2223: r'\ensuremath{\mid}',
0x2224: r'\ensuremath{\nmid}',
0x2225: r'\ensuremath{\parallel}',
0x2226: r'\ensuremath{\nparallel}',
0x2227: r'\ensuremath{\wedge}',
0x2228: r'\ensuremath{\vee}',
0x2229: r'\ensuremath{\cap}',
0x222A: r'\ensuremath{\cup}',
0x222B: r'\ensuremath{\int}',
0x222C: r'\ensuremath{\iint}',
0x222D: r'\ensuremath{\iiint}',
0x222E: r'\ensuremath{\oint}',
#0x222F: SURFACE INTEGRAL
#0x2230: VOLUME INTEGRAL
#0x2231: CLOCKWISE INTEGRAL
#0x2232: CLOCKWIZSE CONTOUR INTEGRAL
#0x2233: ANTICLOCKWISE CONTOUR INTEGRAL
0x2234: r'\ensuremath{\therefore}',
0x2235: r'\ensuremath{\because}',
0x2236: r'\ensuremath{:}',
0x2237: r'\ensuremath{::}',
#0x2238: DOT MINUS
#...
0x223C: r'\ensuremath{\sim}',
0x223D: r'\ensuremath{\backsim}',
#
0x2248: r'\ensuremath{\approx}',
#
0x2260: r'\ensuremath{\neq}',
0x2261: r'\ensuremath{\equiv}',
0x2262: r'\ensuremath{\not\equiv}',
#0x2263: STRICTLY EQUIVALENT TO
0x2264: r'\ensuremath{\leq}',
0x2265: r'\ensuremath{\geq}',
0x2266: r'\ensuremath{\leqq}',
0x2267: r'\ensuremath{\geqq}',
0x2268: r'\ensuremath{\lneqq}',
0x2269: r'\ensuremath{\gneqq}',
0x226A: r'\ensuremath{\ll}',
0x226B: r'\ensuremath{\gg}',
#0x226C: BETWEEN
#0x226D: NOT EQUIVLAENT TO
0x226E: r'\ensuremath{\nless}',
0x226F: r'\ensuremath{\ngtr}',
0x2270: r'\ensuremath{\nleq}',
0x2271: r'\ensuremath{\ngeq}',
0x2272: r'\ensuremath{\lesssim}',
0x2273: r'\ensuremath{\gtrsim}',
0x2274: r'\ensuremath{\not\lesssim}',
0x2275: r'\ensuremath{\not\gtrsim}',
0x2276: r'\ensuremath{\lessgtr}',
0x2277: r'\ensuremath{\gtrless}',
#0x2278: NEITHER LESS-THAN NOR GREATER-THAN
#0x2279: NEITHER GREATER-THAN NOR LESS-THAN
0x227A: r'\ensuremath{\prec}',
0x227B: r'\ensuremath{\succ}',
0x227C: r'\ensuremath{\preceq}',
0x227D: r'\ensuremath{\succeq}',
0x227E: r'\ensuremath{\precsim}',
0x227F: r'\ensuremath{\succsim}',
0x2280: r'\ensuremath{\nprec}',
0x2281: r'\ensuremath{\nsucc}',
0x2282: r'\ensuremath{\subset}',
0x2283: r'\ensuremath{\supset}',
0x2284: r'\ensuremath{\not\subset}',
0x2285: r'\ensuremath{\not\supset}',
0x2286: r'\ensuremath{\subseteq}',
0x2287: r'\ensuremath{\supseteq}',
0x2288: r'\ensuremath{\nsubseteq}',
0x2289: r'\ensuremath{\nsupseteq}',
0x228A: r'\ensuremath{\subsetneq}',
0x228B: r'\ensuremath{\supsetneq}',
#...
0x2293: r'\ensuremath{\sqcap}',
0x2294: r'\ensuremath{\sqcup}',
0x2295: r'\ensuremath{\oplus}',
0x2296: r'\ensuremath{\ominus}',
0x2297: r'\ensuremath{\otimes}',
0x2298: r'\ensuremath{\oslash}',
0x2299: r'\ensuremath{\odot}',
# ...
0x22C0: r'\ensuremath{\bigwedge}',
0x22C1: r'\ensuremath{\bigvee}',
0x22C2: r'\ensuremath{\bigcap}',
0x22C3: r'\ensuremath{\bigcup}',
0x22C4: r'\ensuremath{\diamond}',
0x22C5: r'\ensuremath{\cdot}',
0x22C6: r'\ensuremath{\star}',
0x22C7: r'\ensuremath{\divideontimes}',
0x22C8: r'\ensuremath{\bowtie}',
0x22C9: r'\ensuremath{\ltimes}',
0x22CA: r'\ensuremath{\rtimes}',
0x22CB: r'\ensuremath{\leftthreetimes}',
0x22CC: r'\ensuremath{\rightthreetimes}',
# ...
0x22EE: r'\ensuremath{\vdots}',
0x22EF: r'\ensuremath{\cdots}',
0x22F0: r'\ensuremath{\udots}',
0x22F1: r'\ensuremath{\ddots}',
# ...


9001:'\\textlangle', # 0x2329
9002:'\\textrangle',
9250:'\\textblank',
9251:'\\textvisiblespace',
9702:'\\textopenbullet',
9711:'\\textbigcircle',
9834:'\\textmusicalnote', # 0x266A


0x27E8: r'\ensureamth{\langle}', # MATHEMATICAL LEFT ANGLE BRACKET
0x27E9: r'\ensureamth{\rangle}', # MATHEMATICAL RIGHT ANGLE BRACKET

# Supplemental Mathematical Operators U+2AXX
0x2A7D: r'\ensuremath{\leqslant}',
0x2A7E: r'\ensuremath{\geqslant}',

# CJK Symbols Punktuation (!) U+3000 : for \langle/\rangle
0x3008: r'\ensuremath{\langle}',
0x3009: r'\ensuremath{\rangle}',

# ligatures
0xFB00: r'ff', # LATIN SMALL LIGATURE FF
0xFB01: r'fi', # LATIN SMALL LIGATURE FI
0xFB02: r'fl', # LATIN SMALL LIGATURE FL
0xFB03: r'ffi', # LATIN SMALL LIGATURE FFI
0xFB04: r'ffl', # LATIN SMALL LIGATURE FFL


# Mathematical Alphanumeric Symbols
0x1D400: r'\ensuremath{\mathbf{A}}', # MATHEMATICAL BOLD CAPITAL A
0x1D401: r'\ensuremath{\mathbf{B}}', # MATHEMATICAL BOLD CAPITAL B
0x1D402: r'\ensuremath{\mathbf{C}}', # MATHEMATICAL BOLD CAPITAL C
0x1D403: r'\ensuremath{\mathbf{D}}', # MATHEMATICAL BOLD CAPITAL D
0x1D404: r'\ensuremath{\mathbf{E}}', # MATHEMATICAL BOLD CAPITAL E
0x1D405: r'\ensuremath{\mathbf{F}}', # MATHEMATICAL BOLD CAPITAL F
0x1D406: r'\ensuremath{\mathbf{G}}', # MATHEMATICAL BOLD CAPITAL G
0x1D407: r'\ensuremath{\mathbf{H}}', # MATHEMATICAL BOLD CAPITAL H
0x1D408: r'\ensuremath{\mathbf{I}}', # MATHEMATICAL BOLD CAPITAL I
0x1D409: r'\ensuremath{\mathbf{J}}', # MATHEMATICAL BOLD CAPITAL J
0x1D40A: r'\ensuremath{\mathbf{K}}', # MATHEMATICAL BOLD CAPITAL K
0x1D40B: r'\ensuremath{\mathbf{L}}', # MATHEMATICAL BOLD CAPITAL L
0x1D40C: r'\ensuremath{\mathbf{M}}', # MATHEMATICAL BOLD CAPITAL M
0x1D40D: r'\ensuremath{\mathbf{N}}', # MATHEMATICAL BOLD CAPITAL N
0x1D40E: r'\ensuremath{\mathbf{O}}', # MATHEMATICAL BOLD CAPITAL O
0x1D40F: r'\ensuremath{\mathbf{P}}', # MATHEMATICAL BOLD CAPITAL P
0x1D410: r'\ensuremath{\mathbf{Q}}', # MATHEMATICAL BOLD CAPITAL Q
0x1D411: r'\ensuremath{\mathbf{R}}', # MATHEMATICAL BOLD CAPITAL R
0x1D412: r'\ensuremath{\mathbf{S}}', # MATHEMATICAL BOLD CAPITAL S
0x1D413: r'\ensuremath{\mathbf{T}}', # MATHEMATICAL BOLD CAPITAL T
0x1D414: r'\ensuremath{\mathbf{U}}', # MATHEMATICAL BOLD CAPITAL U
0x1D415: r'\ensuremath{\mathbf{V}}', # MATHEMATICAL BOLD CAPITAL V
0x1D416: r'\ensuremath{\mathbf{W}}', # MATHEMATICAL BOLD CAPITAL W
0x1D417: r'\ensuremath{\mathbf{X}}', # MATHEMATICAL BOLD CAPITAL X
0x1D418: r'\ensuremath{\mathbf{Y}}', # MATHEMATICAL BOLD CAPITAL Y
0x1D419: r'\ensuremath{\mathbf{Z}}', # MATHEMATICAL BOLD CAPITAL Z

0x1D41A: r'\ensuremath{\mathbf{a}}', # MATHEMATICAL BOLD SMALL a
0x1D41B: r'\ensuremath{\mathbf{b}}', # MATHEMATICAL BOLD SMALL b
0x1D41C: r'\ensuremath{\mathbf{c}}', # MATHEMATICAL BOLD SMALL c
0x1D41D: r'\ensuremath{\mathbf{d}}', # MATHEMATICAL BOLD SMALL d
0x1D41E: r'\ensuremath{\mathbf{e}}', # MATHEMATICAL BOLD SMALL e
0x1D41F: r'\ensuremath{\mathbf{f}}', # MATHEMATICAL BOLD SMALL f
0x1D420: r'\ensuremath{\mathbf{g}}', # MATHEMATICAL BOLD SMALL g
0x1D421: r'\ensuremath{\mathbf{h}}', # MATHEMATICAL BOLD SMALL h
0x1D422: r'\ensuremath{\mathbf{i}}', # MATHEMATICAL BOLD SMALL i
0x1D423: r'\ensuremath{\mathbf{j}}', # MATHEMATICAL BOLD SMALL j
0x1D424: r'\ensuremath{\mathbf{k}}', # MATHEMATICAL BOLD SMALL k
0x1D425: r'\ensuremath{\mathbf{l}}', # MATHEMATICAL BOLD SMALL l
0x1D426: r'\ensuremath{\mathbf{m}}', # MATHEMATICAL BOLD SMALL m
0x1D427: r'\ensuremath{\mathbf{n}}', # MATHEMATICAL BOLD SMALL n
0x1D428: r'\ensuremath{\mathbf{o}}', # MATHEMATICAL BOLD SMALL o
0x1D429: r'\ensuremath{\mathbf{p}}', # MATHEMATICAL BOLD SMALL p
0x1D42A: r'\ensuremath{\mathbf{q}}', # MATHEMATICAL BOLD SMALL q
0x1D42B: r'\ensuremath{\mathbf{r}}', # MATHEMATICAL BOLD SMALL r
0x1D42C: r'\ensuremath{\mathbf{s}}', # MATHEMATICAL BOLD SMALL s
0x1D42D: r'\ensuremath{\mathbf{t}}', # MATHEMATICAL BOLD SMALL t
0x1D42E: r'\ensuremath{\mathbf{u}}', # MATHEMATICAL BOLD SMALL u
0x1D42F: r'\ensuremath{\mathbf{v}}', # MATHEMATICAL BOLD SMALL v
0x1D430: r'\ensuremath{\mathbf{w}}', # MATHEMATICAL BOLD SMALL w
0x1D431: r'\ensuremath{\mathbf{x}}', # MATHEMATICAL BOLD SMALL x
0x1D432: r'\ensuremath{\mathbf{y}}', # MATHEMATICAL BOLD SMALL y
0x1D433: r'\ensuremath{\mathbf{z}}', # MATHEMATICAL BOLD SMALL z

0x1D434: r'\ensuremath{\mathit{A}}', # MATHEMATICAL ITALIC CAPITAL A
0x1D435: r'\ensuremath{\mathit{B}}', # MATHEMATICAL ITALIC CAPITAL B
0x1D436: r'\ensuremath{\mathit{C}}', # MATHEMATICAL ITALIC CAPITAL C
0x1D437: r'\ensuremath{\mathit{D}}', # MATHEMATICAL ITALIC CAPITAL D
0x1D438: r'\ensuremath{\mathit{E}}', # MATHEMATICAL ITALIC CAPITAL E
0x1D439: r'\ensuremath{\mathit{F}}', # MATHEMATICAL ITALIC CAPITAL F
0x1D43A: r'\ensuremath{\mathit{G}}', # MATHEMATICAL ITALIC CAPITAL G
0x1D43B: r'\ensuremath{\mathit{H}}', # MATHEMATICAL ITALIC CAPITAL H
0x1D43C: r'\ensuremath{\mathit{I}}', # MATHEMATICAL ITALIC CAPITAL I
0x1D43D: r'\ensuremath{\mathit{J}}', # MATHEMATICAL ITALIC CAPITAL J
0x1D43E: r'\ensuremath{\mathit{K}}', # MATHEMATICAL ITALIC CAPITAL K
0x1D43F: r'\ensuremath{\mathit{L}}', # MATHEMATICAL ITALIC CAPITAL L
0x1D440: r'\ensuremath{\mathit{M}}', # MATHEMATICAL ITALIC CAPITAL M
0x1D441: r'\ensuremath{\mathit{N}}', # MATHEMATICAL ITALIC CAPITAL N
0x1D442: r'\ensuremath{\mathit{O}}', # MATHEMATICAL ITALIC CAPITAL O
0x1D443: r'\ensuremath{\mathit{P}}', # MATHEMATICAL ITALIC CAPITAL P
0x1D444: r'\ensuremath{\mathit{Q}}', # MATHEMATICAL ITALIC CAPITAL Q
0x1D445: r'\ensuremath{\mathit{R}}', # MATHEMATICAL ITALIC CAPITAL R
0x1D446: r'\ensuremath{\mathit{S}}', # MATHEMATICAL ITALIC CAPITAL S
0x1D447: r'\ensuremath{\mathit{T}}', # MATHEMATICAL ITALIC CAPITAL T
0x1D448: r'\ensuremath{\mathit{U}}', # MATHEMATICAL ITALIC CAPITAL U
0x1D449: r'\ensuremath{\mathit{V}}', # MATHEMATICAL ITALIC CAPITAL V
0x1D44A: r'\ensuremath{\mathit{W}}', # MATHEMATICAL ITALIC CAPITAL W
0x1D44B: r'\ensuremath{\mathit{X}}', # MATHEMATICAL ITALIC CAPITAL X
0x1D44C: r'\ensuremath{\mathit{Y}}', # MATHEMATICAL ITALIC CAPITAL Y
0x1D44D: r'\ensuremath{\mathit{Z}}', # MATHEMATICAL ITALIC CAPITAL Z

0x1D44E: r'\ensuremath{\mathit{a}}', # MATHEMATICAL ITALIC SMALL a
0x1D44F: r'\ensuremath{\mathit{b}}', # MATHEMATICAL ITALIC SMALL b
0x1D450: r'\ensuremath{\mathit{c}}', # MATHEMATICAL ITALIC SMALL c
0x1D451: r'\ensuremath{\mathit{d}}', # MATHEMATICAL ITALIC SMALL d
0x1D452: r'\ensuremath{\mathit{e}}', # MATHEMATICAL ITALIC SMALL e
0x1D453: r'\ensuremath{\mathit{f}}', # MATHEMATICAL ITALIC SMALL f
0x1D454: r'\ensuremath{\mathit{g}}', # MATHEMATICAL ITALIC SMALL g
0x1D455: r'\ensuremath{\mathit{h}}', # MATHEMATICAL ITALIC SMALL h
0x1D456: r'\ensuremath{\mathit{i}}', # MATHEMATICAL ITALIC SMALL i
0x1D457: r'\ensuremath{\mathit{j}}', # MATHEMATICAL ITALIC SMALL j
0x1D458: r'\ensuremath{\mathit{k}}', # MATHEMATICAL ITALIC SMALL k
0x1D459: r'\ensuremath{\mathit{l}}', # MATHEMATICAL ITALIC SMALL l
0x1D45A: r'\ensuremath{\mathit{m}}', # MATHEMATICAL ITALIC SMALL m
0x1D45B: r'\ensuremath{\mathit{n}}', # MATHEMATICAL ITALIC SMALL n
0x1D45C: r'\ensuremath{\mathit{o}}', # MATHEMATICAL ITALIC SMALL o
0x1D45D: r'\ensuremath{\mathit{p}}', # MATHEMATICAL ITALIC SMALL p
0x1D45E: r'\ensuremath{\mathit{q}}', # MATHEMATICAL ITALIC SMALL q
0x1D45F: r'\ensuremath{\mathit{r}}', # MATHEMATICAL ITALIC SMALL r
0x1D460: r'\ensuremath{\mathit{s}}', # MATHEMATICAL ITALIC SMALL s
0x1D461: r'\ensuremath{\mathit{t}}', # MATHEMATICAL ITALIC SMALL t
0x1D462: r'\ensuremath{\mathit{u}}', # MATHEMATICAL ITALIC SMALL u
0x1D463: r'\ensuremath{\mathit{v}}', # MATHEMATICAL ITALIC SMALL v
0x1D464: r'\ensuremath{\mathit{w}}', # MATHEMATICAL ITALIC SMALL w
0x1D465: r'\ensuremath{\mathit{x}}', # MATHEMATICAL ITALIC SMALL x
0x1D466: r'\ensuremath{\mathit{y}}', # MATHEMATICAL ITALIC SMALL y
0x1D467: r'\ensuremath{\mathit{z}}', # MATHEMATICAL ITALIC SMALL z

0x1D468: r'\ensuremath{\boldsymbol{\mathit{A}}}', # MATHEMATICAL BOLD ITALIC CAPITAL A
0x1D469: r'\ensuremath{\boldsymbol{\mathit{B}}}', # MATHEMATICAL BOLD ITALIC CAPITAL B
0x1D46A: r'\ensuremath{\boldsymbol{\mathit{C}}}', # MATHEMATICAL BOLD ITALIC CAPITAL C
0x1D46B: r'\ensuremath{\boldsymbol{\mathit{D}}}', # MATHEMATICAL BOLD ITALIC CAPITAL D
0x1D46C: r'\ensuremath{\boldsymbol{\mathit{E}}}', # MATHEMATICAL BOLD ITALIC CAPITAL E
0x1D46D: r'\ensuremath{\boldsymbol{\mathit{F}}}', # MATHEMATICAL BOLD ITALIC CAPITAL F
0x1D46E: r'\ensuremath{\boldsymbol{\mathit{G}}}', # MATHEMATICAL BOLD ITALIC CAPITAL G
0x1D46F: r'\ensuremath{\boldsymbol{\mathit{H}}}', # MATHEMATICAL BOLD ITALIC CAPITAL H
0x1D470: r'\ensuremath{\boldsymbol{\mathit{I}}}', # MATHEMATICAL BOLD ITALIC CAPITAL I
0x1D471: r'\ensuremath{\boldsymbol{\mathit{J}}}', # MATHEMATICAL BOLD ITALIC CAPITAL J
0x1D472: r'\ensuremath{\boldsymbol{\mathit{K}}}', # MATHEMATICAL BOLD ITALIC CAPITAL K
0x1D473: r'\ensuremath{\boldsymbol{\mathit{L}}}', # MATHEMATICAL BOLD ITALIC CAPITAL L
0x1D474: r'\ensuremath{\boldsymbol{\mathit{M}}}', # MATHEMATICAL BOLD ITALIC CAPITAL M
0x1D475: r'\ensuremath{\boldsymbol{\mathit{N}}}', # MATHEMATICAL BOLD ITALIC CAPITAL N
0x1D476: r'\ensuremath{\boldsymbol{\mathit{O}}}', # MATHEMATICAL BOLD ITALIC CAPITAL O
0x1D477: r'\ensuremath{\boldsymbol{\mathit{P}}}', # MATHEMATICAL BOLD ITALIC CAPITAL P
0x1D478: r'\ensuremath{\boldsymbol{\mathit{Q}}}', # MATHEMATICAL BOLD ITALIC CAPITAL Q
0x1D479: r'\ensuremath{\boldsymbol{\mathit{R}}}', # MATHEMATICAL BOLD ITALIC CAPITAL R
0x1D47A: r'\ensuremath{\boldsymbol{\mathit{S}}}', # MATHEMATICAL BOLD ITALIC CAPITAL S
0x1D47B: r'\ensuremath{\boldsymbol{\mathit{T}}}', # MATHEMATICAL BOLD ITALIC CAPITAL T
0x1D47C: r'\ensuremath{\boldsymbol{\mathit{U}}}', # MATHEMATICAL BOLD ITALIC CAPITAL U
0x1D47D: r'\ensuremath{\boldsymbol{\mathit{V}}}', # MATHEMATICAL BOLD ITALIC CAPITAL V
0x1D47E: r'\ensuremath{\boldsymbol{\mathit{W}}}', # MATHEMATICAL BOLD ITALIC CAPITAL W
0x1D47F: r'\ensuremath{\boldsymbol{\mathit{X}}}', # MATHEMATICAL BOLD ITALIC CAPITAL X
0x1D480: r'\ensuremath{\boldsymbol{\mathit{Y}}}', # MATHEMATICAL BOLD ITALIC CAPITAL Y
0x1D481: r'\ensuremath{\boldsymbol{\mathit{Z}}}', # MATHEMATICAL BOLD ITALIC CAPITAL Z

0x1D482: r'\ensuremath{\boldsymbol{\mathit{a}}}', # MATHEMATICAL BOLD ITALIC SMALL a
0x1D483: r'\ensuremath{\boldsymbol{\mathit{b}}}', # MATHEMATICAL BOLD ITALIC SMALL b
0x1D484: r'\ensuremath{\boldsymbol{\mathit{c}}}', # MATHEMATICAL BOLD ITALIC SMALL c
0x1D485: r'\ensuremath{\boldsymbol{\mathit{d}}}', # MATHEMATICAL BOLD ITALIC SMALL d
0x1D486: r'\ensuremath{\boldsymbol{\mathit{e}}}', # MATHEMATICAL BOLD ITALIC SMALL e
0x1D487: r'\ensuremath{\boldsymbol{\mathit{f}}}', # MATHEMATICAL BOLD ITALIC SMALL f
0x1D488: r'\ensuremath{\boldsymbol{\mathit{g}}}', # MATHEMATICAL BOLD ITALIC SMALL g
0x1D489: r'\ensuremath{\boldsymbol{\mathit{h}}}', # MATHEMATICAL BOLD ITALIC SMALL h
0x1D48A: r'\ensuremath{\boldsymbol{\mathit{i}}}', # MATHEMATICAL BOLD ITALIC SMALL i
0x1D48B: r'\ensuremath{\boldsymbol{\mathit{j}}}', # MATHEMATICAL BOLD ITALIC SMALL j
0x1D48C: r'\ensuremath{\boldsymbol{\mathit{k}}}', # MATHEMATICAL BOLD ITALIC SMALL k
0x1D48D: r'\ensuremath{\boldsymbol{\mathit{l}}}', # MATHEMATICAL BOLD ITALIC SMALL l
0x1D48E: r'\ensuremath{\boldsymbol{\mathit{m}}}', # MATHEMATICAL BOLD ITALIC SMALL m
0x1D48F: r'\ensuremath{\boldsymbol{\mathit{n}}}', # MATHEMATICAL BOLD ITALIC SMALL n
0x1D490: r'\ensuremath{\boldsymbol{\mathit{o}}}', # MATHEMATICAL BOLD ITALIC SMALL o
0x1D491: r'\ensuremath{\boldsymbol{\mathit{p}}}', # MATHEMATICAL BOLD ITALIC SMALL p
0x1D492: r'\ensuremath{\boldsymbol{\mathit{q}}}', # MATHEMATICAL BOLD ITALIC SMALL q
0x1D493: r'\ensuremath{\boldsymbol{\mathit{r}}}', # MATHEMATICAL BOLD ITALIC SMALL r
0x1D494: r'\ensuremath{\boldsymbol{\mathit{s}}}', # MATHEMATICAL BOLD ITALIC SMALL s
0x1D495: r'\ensuremath{\boldsymbol{\mathit{t}}}', # MATHEMATICAL BOLD ITALIC SMALL t
0x1D496: r'\ensuremath{\boldsymbol{\mathit{u}}}', # MATHEMATICAL BOLD ITALIC SMALL u
0x1D497: r'\ensuremath{\boldsymbol{\mathit{v}}}', # MATHEMATICAL BOLD ITALIC SMALL v
0x1D498: r'\ensuremath{\boldsymbol{\mathit{w}}}', # MATHEMATICAL BOLD ITALIC SMALL w
0x1D499: r'\ensuremath{\boldsymbol{\mathit{x}}}', # MATHEMATICAL BOLD ITALIC SMALL x
0x1D49A: r'\ensuremath{\boldsymbol{\mathit{y}}}', # MATHEMATICAL BOLD ITALIC SMALL y
0x1D49B: r'\ensuremath{\boldsymbol{\mathit{z}}}', # MATHEMATICAL BOLD ITALIC SMALL z

0x1D49C: r'\ensuremath{\mathscr{A}}', # MATHEMATICAL SCRIPT CAPITAL A
0x1D49D: r'\ensuremath{\mathscr{B}}', # MATHEMATICAL SCRIPT CAPITAL B
0x1D49E: r'\ensuremath{\mathscr{C}}', # MATHEMATICAL SCRIPT CAPITAL C
0x1D49F: r'\ensuremath{\mathscr{D}}', # MATHEMATICAL SCRIPT CAPITAL D
0x1D4A0: r'\ensuremath{\mathscr{E}}', # MATHEMATICAL SCRIPT CAPITAL E
0x1D4A1: r'\ensuremath{\mathscr{F}}', # MATHEMATICAL SCRIPT CAPITAL F
0x1D4A2: r'\ensuremath{\mathscr{G}}', # MATHEMATICAL SCRIPT CAPITAL G
0x1D4A3: r'\ensuremath{\mathscr{H}}', # MATHEMATICAL SCRIPT CAPITAL H
0x1D4A4: r'\ensuremath{\mathscr{I}}', # MATHEMATICAL SCRIPT CAPITAL I
0x1D4A5: r'\ensuremath{\mathscr{J}}', # MATHEMATICAL SCRIPT CAPITAL J
0x1D4A6: r'\ensuremath{\mathscr{K}}', # MATHEMATICAL SCRIPT CAPITAL K
0x1D4A7: r'\ensuremath{\mathscr{L}}', # MATHEMATICAL SCRIPT CAPITAL L
0x1D4A8: r'\ensuremath{\mathscr{M}}', # MATHEMATICAL SCRIPT CAPITAL M
0x1D4A9: r'\ensuremath{\mathscr{N}}', # MATHEMATICAL SCRIPT CAPITAL N
0x1D4AA: r'\ensuremath{\mathscr{O}}', # MATHEMATICAL SCRIPT CAPITAL O
0x1D4AB: r'\ensuremath{\mathscr{P}}', # MATHEMATICAL SCRIPT CAPITAL P
0x1D4AC: r'\ensuremath{\mathscr{Q}}', # MATHEMATICAL SCRIPT CAPITAL Q
0x1D4AD: r'\ensuremath{\mathscr{R}}', # MATHEMATICAL SCRIPT CAPITAL R
0x1D4AE: r'\ensuremath{\mathscr{S}}', # MATHEMATICAL SCRIPT CAPITAL S
0x1D4AF: r'\ensuremath{\mathscr{T}}', # MATHEMATICAL SCRIPT CAPITAL T
0x1D4B0: r'\ensuremath{\mathscr{U}}', # MATHEMATICAL SCRIPT CAPITAL U
0x1D4B1: r'\ensuremath{\mathscr{V}}', # MATHEMATICAL SCRIPT CAPITAL V
0x1D4B2: r'\ensuremath{\mathscr{W}}', # MATHEMATICAL SCRIPT CAPITAL W
0x1D4B3: r'\ensuremath{\mathscr{X}}', # MATHEMATICAL SCRIPT CAPITAL X
0x1D4B4: r'\ensuremath{\mathscr{Y}}', # MATHEMATICAL SCRIPT CAPITAL Y
0x1D4B5: r'\ensuremath{\mathscr{Z}}', # MATHEMATICAL SCRIPT CAPITAL Z

0x1D504: r'\ensuremath{\mathfrak{A}}', # MATHEMATICAL FRAKTUR CAPITAL A
0x1D505: r'\ensuremath{\mathfrak{B}}', # MATHEMATICAL FRAKTUR CAPITAL B
0x1D506: r'\ensuremath{\mathfrak{C}}', # MATHEMATICAL FRAKTUR CAPITAL C
0x1D507: r'\ensuremath{\mathfrak{D}}', # MATHEMATICAL FRAKTUR CAPITAL D
0x1D508: r'\ensuremath{\mathfrak{E}}', # MATHEMATICAL FRAKTUR CAPITAL E
0x1D509: r'\ensuremath{\mathfrak{F}}', # MATHEMATICAL FRAKTUR CAPITAL F
0x1D50A: r'\ensuremath{\mathfrak{G}}', # MATHEMATICAL FRAKTUR CAPITAL G
0x1D50B: r'\ensuremath{\mathfrak{H}}', # MATHEMATICAL FRAKTUR CAPITAL H
0x1D50C: r'\ensuremath{\mathfrak{I}}', # MATHEMATICAL FRAKTUR CAPITAL I
0x1D50D: r'\ensuremath{\mathfrak{J}}', # MATHEMATICAL FRAKTUR CAPITAL J
0x1D50E: r'\ensuremath{\mathfrak{K}}', # MATHEMATICAL FRAKTUR CAPITAL K
0x1D50F: r'\ensuremath{\mathfrak{L}}', # MATHEMATICAL FRAKTUR CAPITAL L
0x1D510: r'\ensuremath{\mathfrak{M}}', # MATHEMATICAL FRAKTUR CAPITAL M
0x1D511: r'\ensuremath{\mathfrak{N}}', # MATHEMATICAL FRAKTUR CAPITAL N
0x1D512: r'\ensuremath{\mathfrak{O}}', # MATHEMATICAL FRAKTUR CAPITAL O
0x1D513: r'\ensuremath{\mathfrak{P}}', # MATHEMATICAL FRAKTUR CAPITAL P
0x1D514: r'\ensuremath{\mathfrak{Q}}', # MATHEMATICAL FRAKTUR CAPITAL Q
0x1D515: r'\ensuremath{\mathfrak{R}}', # MATHEMATICAL FRAKTUR CAPITAL R
0x1D516: r'\ensuremath{\mathfrak{S}}', # MATHEMATICAL FRAKTUR CAPITAL S
0x1D517: r'\ensuremath{\mathfrak{T}}', # MATHEMATICAL FRAKTUR CAPITAL T
0x1D518: r'\ensuremath{\mathfrak{U}}', # MATHEMATICAL FRAKTUR CAPITAL U
0x1D519: r'\ensuremath{\mathfrak{V}}', # MATHEMATICAL FRAKTUR CAPITAL V
0x1D51A: r'\ensuremath{\mathfrak{W}}', # MATHEMATICAL FRAKTUR CAPITAL W
0x1D51B: r'\ensuremath{\mathfrak{X}}', # MATHEMATICAL FRAKTUR CAPITAL X
0x1D51C: r'\ensuremath{\mathfrak{Y}}', # MATHEMATICAL FRAKTUR CAPITAL Y
0x1D51D: r'\ensuremath{\mathfrak{Z}}', # MATHEMATICAL FRAKTUR CAPITAL Z

0x1D51E: r'\ensuremath{\mathfrak{a}}', # MATHEMATICAL FRAKTUR SMALL a
0x1D51F: r'\ensuremath{\mathfrak{b}}', # MATHEMATICAL FRAKTUR SMALL b
0x1D520: r'\ensuremath{\mathfrak{c}}', # MATHEMATICAL FRAKTUR SMALL c
0x1D521: r'\ensuremath{\mathfrak{d}}', # MATHEMATICAL FRAKTUR SMALL d
0x1D522: r'\ensuremath{\mathfrak{e}}', # MATHEMATICAL FRAKTUR SMALL e
0x1D523: r'\ensuremath{\mathfrak{f}}', # MATHEMATICAL FRAKTUR SMALL f
0x1D524: r'\ensuremath{\mathfrak{g}}', # MATHEMATICAL FRAKTUR SMALL g
0x1D525: r'\ensuremath{\mathfrak{h}}', # MATHEMATICAL FRAKTUR SMALL h
0x1D526: r'\ensuremath{\mathfrak{i}}', # MATHEMATICAL FRAKTUR SMALL i
0x1D527: r'\ensuremath{\mathfrak{j}}', # MATHEMATICAL FRAKTUR SMALL j
0x1D528: r'\ensuremath{\mathfrak{k}}', # MATHEMATICAL FRAKTUR SMALL k
0x1D529: r'\ensuremath{\mathfrak{l}}', # MATHEMATICAL FRAKTUR SMALL l
0x1D52A: r'\ensuremath{\mathfrak{m}}', # MATHEMATICAL FRAKTUR SMALL m
0x1D52B: r'\ensuremath{\mathfrak{n}}', # MATHEMATICAL FRAKTUR SMALL n
0x1D52C: r'\ensuremath{\mathfrak{o}}', # MATHEMATICAL FRAKTUR SMALL o
0x1D52D: r'\ensuremath{\mathfrak{p}}', # MATHEMATICAL FRAKTUR SMALL p
0x1D52E: r'\ensuremath{\mathfrak{q}}', # MATHEMATICAL FRAKTUR SMALL q
0x1D52F: r'\ensuremath{\mathfrak{r}}', # MATHEMATICAL FRAKTUR SMALL r
0x1D530: r'\ensuremath{\mathfrak{s}}', # MATHEMATICAL FRAKTUR SMALL s
0x1D531: r'\ensuremath{\mathfrak{t}}', # MATHEMATICAL FRAKTUR SMALL t
0x1D532: r'\ensuremath{\mathfrak{u}}', # MATHEMATICAL FRAKTUR SMALL u
0x1D533: r'\ensuremath{\mathfrak{v}}', # MATHEMATICAL FRAKTUR SMALL v
0x1D534: r'\ensuremath{\mathfrak{w}}', # MATHEMATICAL FRAKTUR SMALL w
0x1D535: r'\ensuremath{\mathfrak{x}}', # MATHEMATICAL FRAKTUR SMALL x
0x1D536: r'\ensuremath{\mathfrak{y}}', # MATHEMATICAL FRAKTUR SMALL y
0x1D537: r'\ensuremath{\mathfrak{z}}', # MATHEMATICAL FRAKTUR SMALL z

0x1D538: r'\ensuremath{\mathbb{A}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL A
0x1D539: r'\ensuremath{\mathbb{B}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL B
0x1D53A: r'\ensuremath{\mathbb{C}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL C
0x1D53B: r'\ensuremath{\mathbb{D}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL D
0x1D53C: r'\ensuremath{\mathbb{E}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL E
0x1D53D: r'\ensuremath{\mathbb{F}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL F
0x1D53E: r'\ensuremath{\mathbb{G}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL G
0x1D53F: r'\ensuremath{\mathbb{H}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL H
0x1D540: r'\ensuremath{\mathbb{I}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL I
0x1D541: r'\ensuremath{\mathbb{J}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL J
0x1D542: r'\ensuremath{\mathbb{K}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL K
0x1D543: r'\ensuremath{\mathbb{L}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL L
0x1D544: r'\ensuremath{\mathbb{M}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL M
0x1D545: r'\ensuremath{\mathbb{N}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL N
0x1D546: r'\ensuremath{\mathbb{O}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL O
0x1D547: r'\ensuremath{\mathbb{P}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL P
0x1D548: r'\ensuremath{\mathbb{Q}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL Q
0x1D549: r'\ensuremath{\mathbb{R}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL R
0x1D54A: r'\ensuremath{\mathbb{S}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL S
0x1D54B: r'\ensuremath{\mathbb{T}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL T
0x1D54C: r'\ensuremath{\mathbb{U}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL U
0x1D54D: r'\ensuremath{\mathbb{V}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL V
0x1D54E: r'\ensuremath{\mathbb{W}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL W
0x1D54F: r'\ensuremath{\mathbb{X}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL X
0x1D550: r'\ensuremath{\mathbb{Y}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL Y
0x1D551: r'\ensuremath{\mathbb{Z}}', # MATHEMATICAL DOUBLE-STRUCK CAPITAL Z

}


