
name: 'deploy-pypi'


on:
  workflow_dispatch: {}

jobs:
  deploy-pypi:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    environment: env-deploy-pypi

    steps:
      - uses: actions/checkout@v4

      - name: 'Set up uv'
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: '${{ matrix.python-version }}'

      - name: 'Build package (sdist & wheel)'
        run: uv build

      - name: 'Publish package'
        run: 'uv publish --token "${{ secrets.PYPI_API_TOKEN }}"'
