
name: 'tests-ci-js'


on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]
  # schedule:
  #   - cron: "13 20 * * 3"

jobs:
  tests-ci-js:

    strategy:
      #fail-fast: true
      matrix:
        python-version:
          - "3.11"
        node-version:
          - "14"
          - "19"
        os:
          - 'ubuntu-latest'

    runs-on: '${{ matrix.os }}'

    steps:
      - uses: actions/checkout@v4

      # Install NodeJS
      - uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'

      - name: 'Setting up some node packages'
        run: 'npm i debug'

      # uv & Python are needed to transpile the Python library
      - name: 'Set up uv'
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: '${{ matrix.python-version }}'

      - name: 'uv sync (with the buildjslib group)'
        run: 'uv sync --frozen --group buildjslib'

      - name: 'Generate pylatexenc JS library'
        working-directory: 'js-transcrypt'
        run: 'uv run --frozen python ./generate_pylatexenc_js.py --compile-tests'

      - name: 'Run JS tests'
        working-directory: 'js-transcrypt'
        run: 'node test-pylatexenc-js/runtests.js'
